api:
  Name: "product-pricing-sys-api"
  Version: "1.0.0"
  status: "Running"


http:
  listener:
    host: "0.0.0.0"
    port: "8082"
    basePath: "/api"
    path: "v1/*"
    readTimeout: "30000"
    keystore:
      path: "certs/listener.jks"
    connection:
      idealTimeout: "40000"
https:
  port: "8082"

  
httpRetry:
  frequency: "2000"
  attempts: "3"
salesforceRetry:
  frequency: "2000"
  attempts: "3"
  objectTTL: "30"
  connectionTimeOut: "10"  
  
step:
  processStart: "Process start"
  processEnd: "Process End"
  flowStart: "Flow Start"
  flowEnd: "Flow End"
  beforeRequest: "Before Request"
  afterRequest: "After Request"
  
errorLogger:
  transactionlevel: "Error"
  status: "Error"
  
apiKit:
  errors: "APIKIT:BAD_REQUEST, APIKIT:NOT_FOUND, APIKIT:METHOD_NOT_ALLOWED, APIKIT:NOT_ACCEPTABLE, APIKIT:UNSUPPORTED_MEDIA_TYPE, APIKIT:NOT_IMPLEMENTED"